name: dotnet build/test on agent.tomwimmenhove.com

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
                key: ${{ secrets.SSH_PRIVATE_KEY }} 
                known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Update source
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} ./prepare_agent.sh ${{ github.event.repository.name }} ${GITHUB_REF##*/}
      - name: Build
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} dotnet build agentrepos/CachePersist.Net
      - name: Run Example
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} dotnet run --project agentrepos/CachePersist.Net/Example
      - name: Run Tests
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} dotnet test agentrepos/CachePersist.Net/Tests
